### ISSUE TITLE
cmake build fails with Lua 5.2?

### ISSUE THREAD

**Issue by joshber** [Neopallium/lua-zmq#30]
Hi. Trying to build on OS X 10.7.4 with gcc 4.2.1, lua 5.2.0, and zmq 2.2.0

Generates the output that follows. My apologies if I'm simply doing something stupid. I suspect the problem lies with the luaL_reg\* declarations that start at src/pre_generated-zmq.nobj.c:189. The canonical typedef is apparently luaL_Reg. In Lua 5.1, lauxlib.h included
# define luaL_reg luaL_Reg

but this is not present in lauxlib.h under Lua 5.2. This was noted when Lua 5.2 was in beta a year ago

http://lua-users.org/lists/lua-l/2011-07/msg00708.html

but seems not to have been changed. My copy of lauxlib.h, installed March of this year, has no lowercase-r compatibility #define

Any chance of a fix? Other than going back to Lua 5.1?

Thanks!
--Josh

[100%] Building C object CMakeFiles/lua-zmq.dir/src/pre_generated-zmq.nobj.c.o
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:189: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘**attribute**’ before ‘_’ token
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c: In function ‘nobj_try_loading_ffi’:
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:398: error: too few arguments to function ‘lua_load’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c: In function ‘obj_type_register_package’:
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:888: error: nested functions are disabled, use -fnested-functions to re-enable
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:888: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:888: error: ‘reg_list’ undeclared (first use in this function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:888: error: (Each undeclared identifier is reported only once
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:888: error: for each function it appears in.)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:888: error: ‘reg_sub_module’ has no member named ‘pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:896: error: ‘reg_sub_module’ has no member named ‘constants’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:896: error: ‘reg_sub_module’ has no member named ‘bidirectional_consts’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c: In function ‘obj_type_register_meta’:
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:902: error: nested functions are disabled, use -fnested-functions to re-enable
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:902: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:902: error: ‘reg_list’ undeclared (first use in this function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:905: error: ‘reg_sub_module’ has no member named ‘pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:911: error: ‘reg_sub_module’ has no member named ‘constants’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:911: error: ‘reg_sub_module’ has no member named ‘bidirectional_consts’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:914: error: ‘reg_sub_module’ has no member named ‘methods’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:918: error: ‘reg_sub_module’ has no member named ‘metas’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c: In function ‘obj_type_register’:
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:926: error: nested functions are disabled, use -fnested-functions to re-enable
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:926: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:926: error: ‘reg_list’ undeclared (first use in this function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:928: error: ‘reg_sub_module’ has no member named ‘bases’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:940: error: ‘reg_sub_module’ has no member named ‘pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:973: error: ‘reg_sub_module’ has no member named ‘methods’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:991: error: ‘reg_sub_module’ has no member named ‘metas’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:1000: error: ‘reg_sub_module’ has no member named ‘constants’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:1000: error: ‘reg_sub_module’ has no member named ‘bidirectional_consts’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c: At top level:
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:5770: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZErrors_pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:5774: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZErrors_methods’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:5779: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZErrors_metas’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6196: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_zmq_msg_t_pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6203: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_zmq_msg_t_methods’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6214: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_zmq_msg_t_metas’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6233: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Socket_pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6237: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Socket_methods’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6394: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Socket_metas’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6413: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Poller_pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6418: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Poller_methods’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6429: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Poller_metas’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6448: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Ctx_pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6452: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Ctx_methods’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6459: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_Ctx_metas’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6478: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_StopWatch_pub_funcs’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6483: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_StopWatch_methods’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6488: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘obj_ZMQ_StopWatch_metas’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6507: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘zmq_function’
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: error: ‘obj_ZErrors_pub_funcs’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: (near initialization for ‘reg_sub_modules[0]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: error: ‘obj_ZErrors_methods’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: (near initialization for ‘reg_sub_modules[0]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: error: ‘obj_ZErrors_metas’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: (near initialization for ‘reg_sub_modules[0]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: (near initialization for ‘reg_sub_modules[0]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: (near initialization for ‘reg_sub_modules[0]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: (near initialization for ‘reg_sub_modules[0]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6694: warning: (near initialization for ‘reg_sub_modules[0]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: error: ‘obj_zmq_msg_t_pub_funcs’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: (near initialization for ‘reg_sub_modules[1]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: error: ‘obj_zmq_msg_t_methods’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: (near initialization for ‘reg_sub_modules[1]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: error: ‘obj_zmq_msg_t_metas’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: (near initialization for ‘reg_sub_modules[1]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: (near initialization for ‘reg_sub_modules[1]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: (near initialization for ‘reg_sub_modules[1]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: (near initialization for ‘reg_sub_modules[1]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6695: warning: (near initialization for ‘reg_sub_modules[1]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: error: ‘obj_ZMQ_Socket_pub_funcs’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: (near initialization for ‘reg_sub_modules[2]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: error: ‘obj_ZMQ_Socket_methods’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: (near initialization for ‘reg_sub_modules[2]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: error: ‘obj_ZMQ_Socket_metas’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: (near initialization for ‘reg_sub_modules[2]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: (near initialization for ‘reg_sub_modules[2]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: (near initialization for ‘reg_sub_modules[2]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: (near initialization for ‘reg_sub_modules[2]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6696: warning: (near initialization for ‘reg_sub_modules[2]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: error: ‘obj_ZMQ_Poller_pub_funcs’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: (near initialization for ‘reg_sub_modules[3]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: error: ‘obj_ZMQ_Poller_methods’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: (near initialization for ‘reg_sub_modules[3]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: error: ‘obj_ZMQ_Poller_metas’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: (near initialization for ‘reg_sub_modules[3]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: (near initialization for ‘reg_sub_modules[3]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: (near initialization for ‘reg_sub_modules[3]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: (near initialization for ‘reg_sub_modules[3]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6697: warning: (near initialization for ‘reg_sub_modules[3]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: error: ‘obj_ZMQ_Ctx_pub_funcs’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: (near initialization for ‘reg_sub_modules[4]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: error: ‘obj_ZMQ_Ctx_methods’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: (near initialization for ‘reg_sub_modules[4]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: error: ‘obj_ZMQ_Ctx_metas’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: (near initialization for ‘reg_sub_modules[4]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: (near initialization for ‘reg_sub_modules[4]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: (near initialization for ‘reg_sub_modules[4]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: (near initialization for ‘reg_sub_modules[4]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6698: warning: (near initialization for ‘reg_sub_modules[4]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: error: ‘obj_ZMQ_StopWatch_pub_funcs’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: (near initialization for ‘reg_sub_modules[5]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: error: ‘obj_ZMQ_StopWatch_methods’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: (near initialization for ‘reg_sub_modules[5]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: error: ‘obj_ZMQ_StopWatch_metas’ undeclared here (not in a function)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: (near initialization for ‘reg_sub_modules[5]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: (near initialization for ‘reg_sub_modules[5]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: (near initialization for ‘reg_sub_modules[5]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: (near initialization for ‘reg_sub_modules[5]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6699: warning: (near initialization for ‘reg_sub_modules[5]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: (near initialization for ‘reg_sub_modules[6]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: (near initialization for ‘reg_sub_modules[6]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: (near initialization for ‘reg_sub_modules[6]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: (near initialization for ‘reg_sub_modules[6]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: (near initialization for ‘reg_sub_modules[6]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: (near initialization for ‘reg_sub_modules[6]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: excess elements in struct initializer
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6700: warning: (near initialization for ‘reg_sub_modules[6]’)
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c: In function ‘luaopen_zmq’:
/Users/josh/dev/lua/lua-zmq/src/pre_generated-zmq.nobj.c:6758: error: ‘zmq_function’ undeclared (first use in this function)
make[2]: **\* [CMakeFiles/lua-zmq.dir/src/pre_generated-zmq.nobj.c.o] Error 1
make[1]: **\* [CMakeFiles/lua-zmq.dir/all] Error 2
make: **\* [all] Error 2
